newIssueWelcomeComment: >
  Hi there!
  
  Thanks a bunch for opening your first issue! :pray:
  As you're new to this repo, we'd like to suggest that you read our [code of conduct](https://github.com/containrrr/watchtower/blob/master/CODE_OF_CONDUCT.md)
  
newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our [contributing guidelines](https://github.com/containrrr/watchtower/blob/master/CONTRIBUTING.md) as well as our [code of conduct](https://github.com/containrrr/watchtower/blob/master/CODE_OF_CONDUCT.md).

firstPRMergeComment: >
  Congrats on merging your first pull request! We are all very proud of you! :sparkles:
